DROP TABLE "IMAGES";
DROP TABLE "CIRCLECOLLECTION";
DROP TABLE "VILLAGE";
DROP TABLE "EXCEL_AT_UPA_42";

DELETE
FROM "USER_SDO_GEOM_METADATA"
WHERE "TABLE_NAME" = 'VILLAGE' AND "COLUMN_NAME" = 'GEOMETRY';

DROP INDEX "VILLAGE_SPATIAL_IDX";
